### PR TITLE
[Needs testing] Prompt to install the application

### PR DESCRIPTION
**Pull request by superrnovae**
This will prompt (unless '-i' flag is passed then it's automatic) the user to install the application to the device. It uses tcprelay.py and usbmux.py from [this project](https://github.com/phx/pyusbmux).   
   
It will use the same method on linux and macos, and will execute dpkg command on ios.   
   
The ssh module will use keys from ~/.ssh directory so this means the user has to generate a pair beforehand. 
   
This also assumes that ssh password is the default one.

### CODE REVIEW

**Comment by itsnebulalol** [comment]
Instead of using ssh keys, it’s probably better to prompt for their ssh password. It’ll most likely be `alpine`

**Comment by superrnovae** [comment]
It will not prompt for root password. If no value is specified will use 'alpine' as default.

**Comment by FreQRiDeR** [comment]
Who jailbreaks their device and doesn't change their root/user password? Noobs maybe? You should fork your own version at this point. If your going to make so many changes to Nebulas project. Running any python scripts in root will only open up our devices to all sorts if security risks and is completely unnecessary. I will have no part in it, honestly. If something goes wrong with transfer, network. Buhbye iphone!

**Comment by itsnebulalol** [comment]
A lot of people keep it as alpine, including me actually. 

Yeah, they could make a fork, but what’s the reason? They’re just making prs for a few features they want added.

**Comment by FreQRiDeR** [comment]
Not to mention, it will be useless in upcoming ios15 jailbreak ( assuming vulnerability still exists? ) as ios 15 has SSV and will no longer allow root access.

**Comment by itsnebulalol** [comment]
Vuln still exists up to 15.4.1, and it’s already being abused with FilzaEscaped and ram disks.

Afaik, procursus’ solution to SSV is to keep all jailbreak stuff in a seperate folder. Theoretically, the script will still work.

**Comment by FreQRiDeR** [comment]
Using root? Ya think?

**Comment by FreQRiDeR** [comment]
Ok, I didn’t read that correctly :)

**Comment by FreQRiDeR** [comment]
I guess this pr is a moot point for me since I’ve been signing apps directly in my phone. I still would not use root for the ssh process. Why would you? Only one word to change in the script I guess? Heck, I don’t even log into my phone using root! Mostly because there is no reason to and I don’t trust myself to not slip something up!

**Comment by superrnovae** [comment]
> I guess this pr is a moot point for me since I’ve been signing apps directly in my phone. I still would not use root for the ssh process. Why would you? Only one word to change in the script I guess? Heck, I don’t even log into my phone using root! Mostly because there is no reason to and I don’t trust myself to not slip something up! 

You're not forced to use the feature. There is a prompt for it. If you don't want deb to be sent over scp and a dpkg command being executed remotely just answer no.

**Comment by FreQRiDeR** [comment]
> It's not using root to run the ssh command but to establish the connection with the device. How else would you connect over ssh without a root password? A key file? But that makes things more complicated for the user.
> 
> I didn't make too many changes to the script. There's like 50 lines of code added. Other changes are just dependencies (tcprelay and usbmux)

by logging into mobile (user acct.) There is a reason github, brew, apt, dpkg does not use root. You are copying the deb over to user area anyway, why login as root? It’s dirty. It’s risky and it’s unnecessary, but it’s your script. Do as you wish. 

I log into my device all the time via sshfs, ssh, sftp and I always log into user (mobile) because that is where everything is anyway. Docs, pics, downloads, etc... I personally wouldn’t touch a script I downloaded off the internetwith a ten foot pole if it prompted me to enter my root password. Not just for security reasons but what if the script is faulty? Ee’re on GitHub afterall! 🤣 It’s just unprofessional man.

**Comment by FreQRiDeR** [comment]
Try it. Just change ‘root’ to ‘mobile’ in your script. :)

**Comment by superrnovae** [comment]
> Try it. Just change ‘root’ to ‘mobile’ in your script. :)

that does not grant superuser privileges to run the 'dpkg' command.

**Comment by superrnovae** [comment]
> There is a reason github, brew, apt, dpkg does not use root.

What does any of them have to do with installing a deb file on an ios device?

>  why login as root? It’s dirty. It’s risky and it’s unnecessary, 

Because otherwise I would be unable to run the 'dpkg -i file.deb' command.

> I personally wouldn’t touch a script I downloaded off the internet with a ten foot pole if it prompted me to enter my root password.

Good for you. You'd have to learn to read python first and understand what the script does.

> It’s just unprofessional man.

Whatever makes you happy.

**Comment by FreQRiDeR** [comment]
Look, I like your idea. I’m not trying to diss you but you don’t need superuser privilege to install debs via dpkg. Sileo, Cydia never ask for elevated privileges and they install debs all day. It’s just not customary for apps to request root passwords. Especially in ios where any wrong edit or corruption to root (system files) can brick the device! Believe me. I know! 🙄 You won’t be able to enter DFU to restore even! 

Now that I think about it, you have a valid point. I have sudo installed on my phone (which is not active by default!) so I am able to run things as admin vs su. That may be the reason why you need to run su dpkg. I just assume people who run terminal commands on their jb phones activate sudo and you know, change their root/user passwords? 🤓

**Comment by superrnovae** [comment]
> I like your idea. I’m not trying to diss you but you don’t need superuser privilege to install debs via dpkg.

yes you do. 

> Sileo, Cydia never ask for elevated privileges and they install debs all day. 

Both have superuser rights, otherwise they wouldn't be able to install tweaks using dpkg.

> It’s just not customary for apps to request root passwords. 

There is a prompt asking if a user wants to install, and if he does agree he will be asked to provide a password. 

> Especially in ios where any wrong edit or corruption to root (system files) can brick the device! 

The script does not touch the root partition.

> I just assume people who run terminal commands on their jb phones activate sudo and you know, change their root/user passwords?

Some do, most leave it as default.

**Comment by FreQRiDeR** [comment]
You don’t need su to use dpkg. You can do it with sudo. I do it all the time. 

Why did you pull your pull request? I hope I didn’t hurt your feelings! 😕Sorry if I did!

**Comment by superrnovae** [comment]
> You don’t need su to use dpkg. You can do it with sudo. I do it all the time.

sudo dpkg yields a "sudo command not found" on my device.

> Why did you pull your pull request?

To be more professional.

**Comment by FreQRiDeR** [comment]
Like I mentioned before, sudo is not active by default. There is a sudo package you can install or you can add user ‘mobile’ to Sudoers file with terminal. Why it is not active by default, like every other OS? I have no idea? Easier to use root, I suppose? 😜

**Comment by FreQRiDeR** [comment]
Or grab sudo dependency like you did usbmux etc..?

**Comment by FreQRiDeR** [comment]
sudo - sileo://package/sudo - from https://apt.procurs.us/dists/iphoneos-arm64/1700

I forgot I had to install sudo. I have had it for so long. Sorry about confusion.

**Comment by superrnovae** [comment]
> Or grab sudo dependency like you did usbmux etc..?

That would require me to use su to install a sudo package, which defeats the purpose.

**Comment by FreQRiDeR** [comment]
😅 good point! Lol. Man, I don’t even like signing into my phone via usb as usbmux crashes on my phone all the time. Not sure why? It shows up in crashreporter a lot! A wireless drop option would be pretty cool! (Hint, hint...)

**Comment by superrnovae** [comment]
It's not going to work. Unless mobile user is in the sudoers file, the sudo command will fail. The only choice is to fall back to su.

**Comment by itsnebulalol** [comment]
@superrnovae, would you like me to merge this?

**Comment by itsnebulalol** [comment]
Just fixed my other device that's strapped with Elucubratus, so I'll try both.

**Comment by FreQRiDeR** [comment]
I would gladly test this but honestly don’t know how to navigate pr’s, checkouts, cherry-picks and all that. Kinda new to github. Need to research gh use more before I can test.

**Comment by superrnovae** [comment]
> I would gladly test this but honestly don’t know how to navigate pr’s, checkouts, cherry-picks and all that. Kinda new to github. Need to research gh use more before I can test.

You can clone my repository, specifically the install branch using this command:

git clone -b install https://github.com/superrnovae/permasigner.git

**Comment by FreQRiDeR** [comment]
I am getting this error?
---------------------------
terramoda@terraMODAs-Mac-Pro permasigner % python3 main.py --debug
  File "/Users/terramoda/permasigner/main.py", line 535
    subprocess.run(f'sudo dpkg -i output/{app_name.replace(' ', '')}.deb'.split(), stdout=PIPE, stderr=PIPE)
                                                                         ^
SyntaxError: f-string: unmatched '('
terramoda@terraMODAs-Mac-Pro permasigner % python3 main.py --debug
  File "/Users/terramoda/permasigner/main.py", line 535
    subprocess.run(f'sudo dpkg -i output/{app_name.replace(' ', '')}.deb'.split(), stdout=PIPE, stderr=PIPE)
                                                                         ^
SyntaxError: f-string: unmatched '('
terramoda@terraMODAs-Mac-Pro permasigner %

**Comment by superrnovae** [comment]
@[FreQRiDeR](https://github.com/FreQRiDeR) 'git pull' and try again

**Comment by FreQRiDeR** [comment]
prompted to connect as 'mobile' but still prompts dpkg with 'su' instead of 'sudo'
----------------------------------------------------------------
[*] Packaging the deb file...
[DEBUG] Checking if command dpkg-deb is in PATH...
[DEBUG] Running command: dpkg-deb -Zxz --root-owner-group -b /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmphmgfrrqz/deb output/E6B.deb
[?] Would you like install the application to your device? [y, n]: y
Found a connected device
[*] Installing E6B to the device
Relaying TCP connection
[DEBUG] Running command: ./utils/tcprelay.py -t 22:2222
Please provide your user password (default = alpine): 
Sending E6B.deb to device
User is not in sudoers, using su instead
su -c 'dpkg -i /var/mobile/Documents/E6B.deb'
%                                                                               
 

iPhone:~ mobile% su -c 'dpkg -i /var/mobile/Documents/E6B.deb'

su: illegal option -- c
usage: su [-] [-flm] [login [args]]
%                                                                               
 

iPhone:~ mobile% 

[*] We are finished!
[*] The application was installed to your device, no further steps are required!
[*] The app will continue to work when rebooted to stock.
[*] Output file: output/E6B.deb
terramoda@terraMODAs-Mac-Pro permasigner %

**Comment by superrnovae** [comment]
I wonder what changed, it was definitely using Audi in your previous comment. Also, seems like not every jailbreak has -c flag for su.

**Comment by FreQRiDeR** [comment]
I definitely do. I was able to run sudo dpkg via ssh and if you look, I am logged in as mobile, not root. 
----------------------------------------------------------------------------------------------------Last login: Sun Jul 17 12:49:19 on ttys001
terramoda@terraMODAs-Mac-Pro ~ % ssh mobile@172.20.10.1
(mobile@172.20.10.1) Password for mobile@iPhone:
iPhone:~ mobile% sudo dpkg
[sudo] password for mobile: 
dpkg: error: need an action option

Type dpkg --help for help about installing and deinstalling packages [*];
Use 'apt' or 'aptitude' for user-friendly package management;
Type dpkg -Dhelp for a list of dpkg debug flag values;
Type dpkg --force-help for a list of forcing options;
Type dpkg-deb --help for help about manipulating *.deb files;

**Comment by superrnovae** [comment]
What's the output of `sudo -v` and `echo $?`. Also, can you run any sudo command afterwards or do you get timed out?

**Comment by FreQRiDeR** [comment]
iPhone:~ mobile% sudo -v
[sudo] password for mobile: 
iPhone:~ mobile% sudo echo $
$
iPhone:~ mobile% dpkg --install
dpkg: error: requested operation requires superuser privilege
iPhone:~ mobile% sudo dpkg --install
dpkg: error: --install needs at least one package archive file argument

I don’t believe it times out?

**Comment by superrnovae** [comment]
> I don’t believe it times out?
could you do 'git pull' and try one more time?

**Comment by FreQRiDeR** [comment]
The script executes without error, prompts for mobile but fails to install anything. 
———————————————————————

Last login: Sun Jul 17 21:45:32 on ttys000
terramoda@terraMODAs-Mac-Pro ~ % cd permasigner
terramoda@terraMODAs-Mac-Pro permasigner % python3 main.py --debug
IPA Permasigner | Version install-2f46623
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Checking if command dpkg-deb is in PATH...
[?] Would you like to use an IPA stored on the web, or on your system? [external, local] local
[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /Users/terramoda/Documents/IPA/StrelokPro.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -S/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmplxvy6q2c/entitlements.plist -M -Kdev_certificate.p12 ''/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmplxvy6q2c/deb/Applications/StrelokPro.app''
[DEBUG] Frameworks path exists
[DEBUG] Executable found in the ObjectiveDropboxOfficial.framework
Signing executable in ObjectiveDropboxOfficial.framework
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmplxvy6q2c/deb/Applications/StrelokPro.app/Frameworks/ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial

[*] Packaging the deb file...
[DEBUG] Checking if command dpkg-deb is in PATH...
[DEBUG] Running command: dpkg-deb -Zxz --root-owner-group -b /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmplxvy6q2c/deb output/StrelokPro.deb
[?] Would you like install the application to your device? [y, n]: y
Found a connected device
[*] Installing StrelokPro to the device
Relaying TCP connection
[DEBUG] Running command: ./utils/tcprelay.py -t 22:2222
Please provide your user password (default = alpine): 
Sending StrelokPro.deb to device
User is in sudoers, using sudo
sudo dpkg -i /var/mobile/Documents/StrelokPro.deb
%                                                                               
 

iPhone:~ mobile% sudo dpkg -i /var/mobile/Documents/StrelokPro.deb

[sudo] password for mobile: 

[*] We are finished!
[*] The application was installed to your device, no further steps are required!
[*] The app will continue to work when rebooted to stock.
[*] Output file: output/StrelokPro.deb
terramoda@terraMODAs-Mac-Pro permasigner % 
——————————————————————————

However, ssh’ing and running dpkg manually logged in as mobile works.

—————————————————————————————————

terramoda@terraMODAs-Mac-Pro permasigner % ssh mobile@iPhone.local
(mobile@iphone.local) Password for mobile@iPhone:
iPhone:~ mobile% sudo dpkg -i /var/mobile/Documents/StrelokPro.deb
[sudo] password for mobile: 
Selecting previously unselected package mobi.borisov.strelokpro.
(Reading database ... 20491 files and directories currently installed.)
Preparing to unpack .../Documents/StrelokPro.deb ...
Unpacking mobi.borisov.strelokpro (6.39) ...
Setting up mobi.borisov.strelokpro (6.39) ...
Processing triggers for uikittools (2.1.1) ...
iPhone:~ mobile%

**Comment by superrnovae** [comment]
It doesn't check for lowercase password prompt. I will fix it.

**Comment by superrnovae** [comment]
It checks for both cases now.

**Comment by superrnovae** [comment]
> The script executes without error, prompts for mobile but fails to install anything. 
   
It should work now. Do a `git pull`. It's the last time, I promise xD

**Comment by itsnebulalol** [comment]
I know i’m late, but `su -c` didn’t work because it’s supposed to be `su root -c`

**Comment by FreQRiDeR** [comment]
It now reads database but still fails to install? 
----------------------------------------------------

Last login: Mon Jul 18 10:19:38 on console
terramoda@Mac-DaDDY ~ % cd permasigner                                      
terramoda@Mac-DaDDY permasigner % git pull               
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), 952 bytes | 238.00 KiB/s, done.
From https://github.com/superrnovae/permasigner
   2f46623..985e48e  install    -> origin/install
Updating 2f46623..985e48e
Fast-forward
 main.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
terramoda@Mac-DaDDY permasigner % python3 main.py --debug
IPA Permasigner | Version install-985e48e
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Checking if command dpkg-deb is in PATH...
[?] Would you like to use an IPA stored on the web, or on your system? [external, local] local
[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /Users/terramoda/Documents/IPA/StrelokPro.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -S/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpqhvzstg_/entitlements.plist -M -Kdev_certificate.p12 ''/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpqhvzstg_/deb/Applications/StrelokPro.app''
[DEBUG] Frameworks path exists
[DEBUG] Executable found in the ObjectiveDropboxOfficial.framework
Signing executable in ObjectiveDropboxOfficial.framework
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpqhvzstg_/deb/Applications/StrelokPro.app/Frameworks/ObjectiveDropboxOfficial.framework/ObjectiveDropboxOfficial

[*] Packaging the deb file...
[DEBUG] Checking if command dpkg-deb is in PATH...
[DEBUG] Running command: dpkg-deb -Zxz --root-owner-group -b /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpqhvzstg_/deb output/StrelokPro.deb
[?] Would you like install the application to your device? [y, n]: y
Found a connected device
[*] Installing StrelokPro to the device
Relaying TCP connection
[DEBUG] Running command: ./utils/tcprelay.py -t 22:2222
Please provide your user password (default = alpine): 
Sending StrelokPro.deb to device
User is in sudoers, using sudo
Password: 

Selecting previously unselected package mobi.borisov.strelokpro.
(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 25%
(Reading database ... 30%
(Reading database ... 35%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 50%
(Reading database ... 55%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 20491 files and directories currently installed.)
Preparing to unpack .../Documents/StrelokPro.deb ...
Unpacking mobi.borisov.strelokpro (6.39) ...

[*] We are finished!
[*] The application was installed to your device, no further steps are required!
[*] The app will continue to work when rebooted to stock.
[*] Output file: output/StrelokPro.deb
terramoda@Mac-DaDDY permasigner %

**Comment by FreQRiDeR** [comment]
also script broke dpkg and I had to run sudo dpkg --configure -a to fix it. You see why I don't like running commands in root? Especially when testing things! :| The failed install left broken deb package, not allowing apt to work until I reconfigured dpkg. I installed the deb with files and it works fine.

**Comment by superrnovae** [comment]
I managed to reproduce the issue. You may run `git pull` and try again.

**Comment by FreQRiDeR** [comment]
0% Working... LoL. Well it didn't break dpkg this time. Still no install?
Last login: Mon Jul 18 11:37:00 on ttys000
terramoda@Mac-DaDDY ~ % cd permasigner         
terramoda@Mac-DaDDY permasigner % git pull               
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 3 (delta 2), reused 3 (delta 2), pack-reused 0
Unpacking objects: 100% (3/3), 1.12 KiB | 286.00 KiB/s, done.
From https://github.com/superrnovae/permasigner
   985e48e..b9f18d1  install    -> origin/install
Updating 985e48e..b9f18d1
Fast-forward
 main.py | 18 +++++++++++-------
 1 file changed, 11 insertions(+), 7 deletions(-)
terramoda@Mac-DaDDY permasigner % python3 main.py --debug
IPA Permasigner | Version install-b9f18d1
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Checking if command dpkg-deb is in PATH...
[?] Would you like to use an IPA stored on the web, or on your system? [external, local] local
[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /Users/terramoda/Documents/IPA/E6B_1.9.0_Telefonbuchios14ok.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...

[*] Signing app...
Signing with ldid...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -S/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/entitlements.plist -M -Kdev_certificate.p12 ''/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app''
[DEBUG] Frameworks path exists
Signing dylib libswiftCoreImage.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftCoreImage.dylib'
Signing dylib libswiftObjectiveC.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftObjectiveC.dylib'
Signing dylib libswiftCore.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftCore.dylib'
Signing dylib libswiftCoreGraphics.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftCoreGraphics.dylib'
Signing dylib libswiftUIKit.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftUIKit.dylib'
Signing dylib libswiftMetal.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftMetal.dylib'
Signing dylib libswiftCoreData.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftCoreData.dylib'
Signing dylib libswiftDispatch.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftDispatch.dylib'
Signing dylib libswiftos.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftos.dylib'
Signing dylib libswiftCoreFoundation.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftCoreFoundation.dylib'
Signing dylib libswiftCloudKit.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftCloudKit.dylib'
Signing dylib libswiftDarwin.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftDarwin.dylib'
Signing dylib libswiftContacts.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftContacts.dylib'
Signing dylib libswiftQuartzCore.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftQuartzCore.dylib'
Signing dylib libswiftFoundation.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftFoundation.dylib'
Signing dylib libswiftCoreLocation.dylib...
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 '/var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/libswiftCoreLocation.dylib'
[DEBUG] Executable found in the raygun4apple.framework
Signing executable in raygun4apple.framework
[DEBUG] Checking if command ldid is in PATH...
[DEBUG] Checking ldid output...
[DEBUG] ldid installed is from Procursus!
[DEBUG] Running command: ldid -Kdev_certificate.p12 /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb/Applications/FlightComputer.app/Frameworks/raygun4apple.framework/raygun4apple

[*] Packaging the deb file...
[DEBUG] Checking if command dpkg-deb is in PATH...
[DEBUG] Running command: dpkg-deb -Zxz --root-owner-group -b /var/folders/5q/1p1130k135bg1_3my8bwz4_r0000gn/T/tmpspe9euqx/deb output/E6B.deb
[?] Would you like install the application to your device? [y, n]: y
Found a connected device
[*] Installing E6B to the device
Relaying TCP connection
[DEBUG] Running command: ./utils/tcprelay.py -t 22:2222
Please provide your user password (default = alpine): 
Sending E6B.deb to device
User is in sudoers, using sudo
Password: 

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'com.aeroappstechnology.easy6b' instead of '/var/mobile/Documents/E6B.deb'
The following NEW packages will be installed:
  com.aeroappstechnology.easy6b
0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.
Need to get 0 B/5877 kB of archives.
After this operation, 0 B of additional disk space will be used.
0% [Working]

[*] We are finished!
[*] The application was installed to your device, no further steps are required!
[*] The app will continue to work when rebooted to stock.
[*] Output file: output/E6B.deb
terramoda@Mac-DaDDY permasigner %

**Comment by superrnovae** [comment]
I managed to reproduce the issue. It will not attempt to resolve dependencies with apt command.

**Comment by superrnovae** [comment]
I reverted the previous commit. I have accidentally pushed changes before saving.

**Comment by FreQRiDeR** [comment]
> Edit: thanks for your patience ;)

No problem :) We will get it sorted. I hope I'm not the only one who appreciates sudo implementation!

**Comment by FreQRiDeR** [comment]
It does ask for sudo pw twice. Once for install y/n prompt and once for dpkg command.

**Comment by superrnovae** [comment]
It asks for user password first, then for sudo to execute 'dpkg' command. I was wondering if it asks for sudo password again, after the dpkg command, when it's running 'apt' command.

**Comment by FreQRiDeR** [comment]
Success! Works now! Installed deb just fine! :)

**Comment by FreQRiDeR** [comment]
> It asks for user password first, then for sudo to execute 'dpkg' command. I was wondering if it asks for sudo password again, after the dpkg command, when it's running 'apt' command.

no, just those two times.

**Comment by superrnovae** [comment]
> I actually just updated apt, libapt, etc.. which just dropped, and it worked. Not sure if there was a bug with apt?

Would you be able to manually remove the app, and reinstall using the script, just to make sure that it's working?

**Comment by FreQRiDeR** [comment]
I just tried with a different ipa and it worked fine. There must have been a bug with apt. Fixed now with latest updates.

**Comment by superrnovae** [comment]
Okay. Thank you for testing. I guess it's mergeable now. @itsnebulalol

**Comment by FreQRiDeR** [comment]
> > I actually just updated apt, libapt, etc.. which just dropped, and it worked. Not sure if there was a bug with apt?
> 
> Would you be able to manually remove the app, and reinstall using the script, just to make sure that it's working?

I actually did every time to make sure ;)

**Comment by itsnebulalol** [comment]
Sounds good!

**Comment by FreQRiDeR** [comment]
I wouldn’t advertise that if I were you!

**Pull request merged**
