### PR TITLE
Resolve errors that occur when there are spaces in filename

### PR DESCRIPTION
**Pull request by kylefmohr**
Hello, 

When I first ran this script, it finished creating the .deb successfully, but there were errors in the output that I think would cause issues if I installed the .deb. The errors were caused by the fact that I was running the script on an app which has a .app folder and executable with a space in the name. Here is the full output including those errors, for a fictitious app named "My App"

```
IPA Permasigner - Version ce62d1b
Program created by Nebula | Original scripts created by zhuowei | CoreTrust bypass by Linus Henze

[?] Would you like to use an IPA stored on the web, or on your system? [external, local] local
[*] Created temporary directory.

[?] Paste in the path to an IPA in your file system: /Users/kyle/permasigner/myapp.ipa

[*] Unzipping IPA...

[*] Reading plist...
Found plist!
Executable found.
Found information about the app!

[*] Preparing deb file...
Making directories...
Copying deb file scripts and control...
Copying app files...
Changing deb file scripts permissions...
Changing app executable permissions...
chmod: /var/folders/v_/3s54xln145jg8z_z9kw2mrsr0000gn/T/tmpyu9poc9x/deb/Applications/My: No such file or directory
chmod: App.app/My: No such file or directory
chmod: App: No such file or directory

[*] Signing app...
Signing with ldid...
ldid: /var/folders/v_/3s54xln145jg8z_z9kw2mrsr0000gn/T/tmpyu9poc9x/deb/Applications/My: No such file or directory

[*] Packaging the deb file...

[*] We are finished!
[*] Copy the newly created deb from the output folder to your jailbroken iDevice and install it!
[*] The app will continue to work when rebooted to stock.
```

This PR resolves these error messages by adding single quotes around the pathnames used in the commands.

### CODE REVIEW

**Comment by itsnebulalol** [comment]
Thanks for the pr! But, can you quickly fix the same issue with codesign too, if it’s there? Seems that you only changed up the ldid signer.

**Comment by kylefmohr** [comment]
Oh, sure, good catch! One moment.

**Comment by itsnebulalol** [comment]
Thank you!

**Comment by kylefmohr** [comment]
Thanks for the useful script!

**Comment by itsnebulalol** [comment]
No problem

**Pull request merged**
