### PR TITLE
Conditionally import ssh modules

### PR DESCRIPTION
**Pull request by superrnovae**
Should be closing #41 
   
But needs testing first

### CODE REVIEW

**Comment by itsnebulalol** [comment]
@[

**Comment by superrnovae** [comment]
I have no idea how to conditionally check in requirements.txt. That would require to have a setup.py instead, where we could check for ios, linux, macos and install dependencies respectively.

**Comment by superrnovae** [comment]
@itsnebulalol you can merge it. Will still have to figure out how to conditionally install dependencies.

**Comment by FreQRiDeR** [comment]
I installed clang and libpython-dev on ios but cssi still failed to compile?  Are you sure there is an arm version?

**Pull request merged**
